### ISSUE TITLE
Ability to set opacity of box shadow

### ISSUE THREAD

**Issue by JakesMD** [conceptadev/mix#176]
### Use case

When creating box shadows it's often essential to set an opacity. Shadows are often a similar, slightly transparent color to the object casting the shadow. It seems unnecessary to create an additional color token for that shadow.

In "normal" Flutter code we would set it like this:
```dart
BoxShadow(color: myColor.withOpacity(0.5))
```

But within a `Style` this is no longer possible if we want to use color tokens:
```dart
Style(box.shadow.color.of(myColorToken))
```

### Proposal

Method 1: Create a separate attribute for box shadow opacity.
``` dart
Style(
  box.shadow.color.of(myColorToken),
  box.shadow.opacity(0.5),
)
```

Method 2 (slight overkill): Add opacity to any color attribute:
``` dart
Style(
  box.shadow.color.of(myColorToken).withOpacity(0.5),
)
```

**Comment by leoafarias** [comment]
@JakesMD thanks for the detailed comment. We are considering the creation of `Color` directives, to run transformations essentially. There are two approaches we were considering in order to get your feedback.

Method 1 - Implement `withOpacity` to the ColorRef, which would behave similar to a `Color` class.

```
Style(
  box.shadow.color(myColorToken().withOpacity(0.5)),
)
```

Method 2 - Create a opacity method like you have suggested but have it on the `ColorUtility`

```dart
Style(
  box.shadow.color.of(myColorToken),
  box.shadow.color.withOpacity(0.5),
)
```
